dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
install:
  - if [ -e requirements.txt ]; then pip install -r requirements.txt ; fi
  - if [ -z "$DOVIS" -o "$PKG_COVERAGE" ]; then pip install coverage; fi
  ## getting test deps
  - python setup.py develop easy_install "$(./autogen.sh --get-name)[test]"
script:
  - shyaml --version
  - bin/test
after_success:
  - "bash <(curl -s https://codecov.io/bash)  #dovis: ignore"
  - |
    if [ "$DOVIS" -a -d "$ARTIFACT_DIR" ]; then
        cp ".coverage" "$ARTIFACT_DIR"
        echo "$PWD" > "$ARTIFACT_DIR/cover_path"
    fi

## Ignored by Travis, but used internally to check packaging
dist_check:
  options:
    exclude:
      - ["v:3.6", "pkg:old"]  ## old version is breaking python 3.6 pkg_resources
  tests:
  - label: install
    matrix:
      'yes':
        - label: venv
          matrix:
            'on': |
              pip install virtualenv
              virtualenv /tmp/virtualenv
              . /tmp/virtualenv/bin/activate
            'off': |
              true
        - label: pkg
          matrix:
            old: |
              ## version 10 introduce a bug with d2to1
              pip install setuptools==9.1
              ## some ``python setup.py`` black magic do not work with d2to1 and pip ``6.0.7``
              pip install pip==1.5.6
            docker: |
              ## Using the versions of python docker images
              true
            latest: |
              ## Using the last version of pip and setuptools
              pip install pip --upgrade
              pip install setuptools --upgrade
        - label: method
          matrix:
            setup: python setup.py install
            pip: pip install .
            pip+git: pip install "git+file://$PWD"
            dist:
              dist_files:
                pip install "$DIST_FILE"
        - |
          pip show -f $(./autogen.sh --get-name)
          pip list
      'no':
        - |
          ln -sf $PWD/$(./autogen.sh --get-name) /usr/local/bin/
          pip install pyyaml
          export PYTHONPATH="$PWD"
          touch /tmp/not-installed

  - |
    SRC=$PWD
    cd /tmp
    cat <<EOF | shyaml get-value c.d
    a: b
    c:
      d: 1
    EOF
  - |
    cd /tmp
    echo PYTHONPATH: $PYTHONPATH
    python -c 'import shyaml'
  - |
    [ -e /tmp/not-installed ] || {
        cd "$SRC"
        pip uninstall -y $(./autogen.sh --get-name)
    }
